# Generated by Django 6.0.6 on 2026-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CPF/CNPJ'),
        ),
    ]
