# Generated by Django 6.0.6 on 2026-07-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_client_address_alter_client_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Link de Pagamento'),
        ),
    ]
