# Generated by Django 6.0.6 on 2026-08-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_purchase_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data para Pagar'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
